### ISSUE TITLE
Could you add a doi to the paper you are refering to? I cannot find the paper Hawkins 2012

### ISSUE THREAD

**Issue by RMHogervorst** [bflammers/ANN2#1]
hi bart,

Could you add a link to the papers you've mentioned?

**Comment by bflammers** [comment]
Hi Roel, 

The name of the paper by Hawkins, Williams and Baxter (2002) is "Outlier detection using replicator neural networks". Here is a link: https://link.springer.com/chapter/10.1007/3-540-46145-0_17

Also note the comparative study by the same authors: http://ieeexplore.ieee.org/abstract/document/1184035/

Where did you see the year 2012? In the manual, description replicator(), I mention the correct year. Is there a typo somewhere else in the manual?

**Comment by RMHogervorst** [comment]
I'll check and make a pull request!

**Comment by bflammers** [comment]
Doi of Hawkins paper is added to the description file

Closing
