### ISSUE TITLE
replicator()

### ISSUE THREAD

**Issue by laermbote2** [bflammers/ANN2#10]
Hi Bart, 

where is the function replicator() gone? It is still part of rdocumentation but not in the package anymore?

Thanks

Karsten

**Comment by bflammers** [comment]
Hi Karsten, 

From release v2.0, the replicator() function is not included anymore. You can get the same functionality with the autoencoder() function with argument activ.functions = c('tanh', 'step', 'tanh'). This will construct an autoencoding neural network with three hidden layers with tanh, step function, and tanh activation functions, in that order. See the example below.

The documentation for the replicator() function has also been removed from this version up. 

Best, 

Bart

---
```
library(ANN2)

# Numerical columns from iris data
X <- iris[,1:4]

# Construct and train replicator neural network
RNN <- autoencoder(X = X, 
                   hidden.layers = c(10, 2, 10), 
                   activ.functions = c('tanh', 'step', 'tanh'), 
                   val.prop = 0, 
                   optim.type = 'adam', 
                   n.epochs = 5000)

# Plotting functions
plot(RNN)
reconstruction_plot(RNN, X)
compression_plot(RNN, X, colors=iris$Species, jitter=TRUE)

# Reconstruction function
reconstruct(RNN, X)
```

**Comment by laermbote2** [comment]
Hi Bart,

thanks for the quick answer. Was my expectation.

Karsten

Von: Bart Lammers <notifications@github.com>
Gesendet: Montag, 26. August 2019 09:39
An: bflammers/ANN2 <ANN2@noreply.github.com>
Cc: laermbote2 <karsten_oehler@yahoo.de>; Author <author@noreply.github.com>
Betreff: Re: [bflammers/ANN2] replicator() (#10)


Hi Karsten,

From release v2.0, the replicator() function is not included anymore. You can get the same functionality with the autoencoder() function with argument activ.functions = c('tanh', 'step', 'tanh'). This will construct an autoencoding neural network with three hidden layers with tanh, step function, and tanh activation functions, in that order. See the example below.

The documentation for the replicator() function has also been removed from this version up.

Best,

Bart

________________________________

library(ANN2)



# Numerical columns from iris data

X <- iris[,1:4]



# Construct and train replicator neural network

RNN <- autoencoder(X = X,

                   hidden.layers = c(10, 2, 10),

                   activ.functions = c('tanh', 'step', 'tanh'),

                   val.prop = 0,

                   optim.type = 'adam',

                   n.epochs = 5000)



# Plotting functions

plot(RNN)

reconstruction_plot(RNN, X)

compression_plot(RNN, X, colors=iris$Species, jitter=TRUE)



# Reconstruction function

reconstruct(RNN, X)
